// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@3sixty/data-core";

const MESSAGES = ["must be equal to constant", "must be string", "must be object"];
function createError(instancePath, schemaPath, keyword, params, message) {
	return {
		instancePath,
		schemaPath,
		keyword,
		params,
		["message"]: typeof message === "number" ? MESSAGES[message] : message
	};
}
function pushError(errors, error) {
	if (errors === null) {
		return [error];
	}
	errors.push(error);
	return errors;
}
/**
 * Compiled validator for the VerifiableStorageEntityStorageReceipt schema.
 */
export const CompiledVerifiableStorageEntityStorageReceipt: ICompiledValidator = validate52;

function validate52(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/verifiable-storage/VerifiableStorageEntityStorageReceipt" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate52.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.entityStorageId === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "entityStorageId" },
				"must have required property '" + "entityStorageId" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			if ("https://schema.3sixty.global/verifiable-storage/" !== data["@context"]) {
				const err3 = createError(
					instancePath + "/@context",
					"#/properties/%40context/const",
					"const",
					{ allowedValue: "https://schema.3sixty.global/verifiable-storage/" },
					0
				);
				vErrors = pushError(vErrors, err3);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("VerifiableStorageEntityStorageReceipt" !== data.type) {
				const err4 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "VerifiableStorageEntityStorageReceipt" },
					0
				);
				vErrors = pushError(vErrors, err4);
				errors++;
			}
		}
		if (data.entityStorageId !== undefined) {
			if (typeof data.entityStorageId !== "string") {
				const err5 = createError(
					instancePath + "/entityStorageId",
					"#/properties/entityStorageId/type",
					"type",
					{ type: "string" },
					1
				);
				vErrors = pushError(vErrors, err5);
				errors++;
			}
		}
	} else {
		const err6 = createError(instancePath, "#/type", "type", { type: "object" }, 2);
		vErrors = pushError(vErrors, err6);
		errors++;
	}
	validate52.errors = vErrors;
	return errors === 0;
}
validate52.evaluated = {
	props: { "@context": true, type: true, entityStorageId: true },
	dynamicProps: false,
	dynamicItems: false
};
