// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@3sixty/data-core";

const MESSAGES = [
	"must be equal to constant",
	"must be number",
	"must be string",
	"must be object"
];
function createError(instancePath, schemaPath, keyword, params, message) {
	return {
		instancePath,
		schemaPath,
		keyword,
		params,
		["message"]: typeof message === "number" ? MESSAGES[message] : message
	};
}
function pushError(errors, error) {
	if (errors === null) {
		return [error];
	}
	errors.push(error);
	return errors;
}
/**
 * Compiled validator for the VerifiableStorageIotaReceipt2026 schema.
 */
export const CompiledVerifiableStorageIotaReceipt2026: ICompiledValidator = validate52;

function validate52(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/verifiable-storage/VerifiableStorageIotaReceipt2026" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate52.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.epoch === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "epoch" },
				"must have required property '" + "epoch" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data.digest === undefined) {
			const err3 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "digest" },
				"must have required property '" + "digest" + "'"
			);
			vErrors = pushError(vErrors, err3);
			errors++;
		}
		if (data.network === undefined) {
			const err4 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "network" },
				"must have required property '" + "network" + "'"
			);
			vErrors = pushError(vErrors, err4);
			errors++;
		}
		if (data.objectId === undefined) {
			const err5 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "objectId" },
				"must have required property '" + "objectId" + "'"
			);
			vErrors = pushError(vErrors, err5);
			errors++;
		}
		if (data.smartContractId === undefined) {
			const err6 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "smartContractId" },
				"must have required property '" + "smartContractId" + "'"
			);
			vErrors = pushError(vErrors, err6);
			errors++;
		}
		if (data["@context"] !== undefined) {
			if ("https://schema.3sixty.global/verifiable-storage/" !== data["@context"]) {
				const err7 = createError(
					instancePath + "/@context",
					"#/properties/%40context/const",
					"const",
					{ allowedValue: "https://schema.3sixty.global/verifiable-storage/" },
					0
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("VerifiableStorageIotaReceipt2026" !== data.type) {
				const err8 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "VerifiableStorageIotaReceipt2026" },
					0
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.epoch !== undefined) {
			let data2 = data.epoch;
			if (!(typeof data2 == "number" && isFinite(data2))) {
				const err9 = createError(
					instancePath + "/epoch",
					"#/properties/epoch/type",
					"type",
					{ type: "number" },
					1
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
		}
		if (data.digest !== undefined) {
			if (typeof data.digest !== "string") {
				const err10 = createError(
					instancePath + "/digest",
					"#/properties/digest/type",
					"type",
					{ type: "string" },
					2
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
		}
		if (data.network !== undefined) {
			if (typeof data.network !== "string") {
				const err11 = createError(
					instancePath + "/network",
					"#/properties/network/type",
					"type",
					{ type: "string" },
					2
				);
				vErrors = pushError(vErrors, err11);
				errors++;
			}
		}
		if (data.objectId !== undefined) {
			if (typeof data.objectId !== "string") {
				const err12 = createError(
					instancePath + "/objectId",
					"#/properties/objectId/type",
					"type",
					{ type: "string" },
					2
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.smartContractId !== undefined) {
			if (typeof data.smartContractId !== "string") {
				const err13 = createError(
					instancePath + "/smartContractId",
					"#/properties/smartContractId/type",
					"type",
					{ type: "string" },
					2
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
	} else {
		const err14 = createError(instancePath, "#/type", "type", { type: "object" }, 3);
		vErrors = pushError(vErrors, err14);
		errors++;
	}
	validate52.errors = vErrors;
	return errors === 0;
}
validate52.evaluated = {
	props: {
		"@context": true,
		type: true,
		epoch: true,
		digest: true,
		network: true,
		objectId: true,
		smartContractId: true
	},
	dynamicProps: false,
	dynamicItems: false
};
